server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 192.168.15.135:8848  # nacos地址
    gateway:
      routes:
        - id: cart
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: item
          uri: lb://item-service
          predicates:
            - Path=/items/**,/search/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: pay
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
wm:
  jwt:
    location: classpath:winter-mall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
logging:
  level:
    com.winter: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"