server:
  port: 8084
spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${wm.db.host}:3306/wm-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${wm.db.pw}
  cloud:
    nacos:
      server-addr: 192.168.15.135:8848  # nacos地址
    sentinel:
      transport:
        dashboard: localhost:8090 # 管理台地址
      http-method-specify: true # 开启请求方式前缀
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.winter: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 用户服务接口文档
    description: "用户服务接口文档"
    email: zhanghuyi@itcast.cn
    concat: winter
    url: https://github.com/TuwenMark
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.winter.user.controller
wm:
  jwt:
    location: classpath:winter-mall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m