server:
  port: 8084

wm:
  # 日志相关配置
  swagger:
    title: 用户服务接口文档
    desc: 用户服务接口文档
    interface: com.winter.user.controller
  jwt:
    location: classpath:winter-mall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m